Add message

diff --git a/deploy-infra/action.yml b/deploy-infra/action.yml
--- a/deploy-infra/action.yml
+++ b/deploy-infra/action.yml
@@ -45,7 +45,7 @@ runs:
       run: |
         aws s3api head-object --bucket escribers-infra-tempenv-terraform-state --key state${{ env.TEMPENV_VERSION }}.tfstate --query ETag --output text
       shell: bash
-      
+
     - name: DEBUG ETAG
       run: |
         echo "${{ env.s3_etag }}" 
@@ -60,6 +60,14 @@ runs:
     - name: DEBUG ETAG
       run: |
         echo "${{ env.dyn_digest }}"
+      shell: bash
+
+    - name: Exit if not same
+      if: env.dyn_digest == env.s3_etag
+      run: |
+        echo "ERROR!!!!!"
+        echo "Another deploy still is inprocess. Please wait untill all commits and checks will be passed and restart this workflow"
+        exit 1
       shell: bash
 
 #################################
