Change order for creating dynamodb table

diff --git a/deploy-infra/action.yml b/deploy-infra/action.yml
--- a/deploy-infra/action.yml
+++ b/deploy-infra/action.yml
@@ -85,21 +85,21 @@ runs:
         echo =${{ env.DYN_DIGEST }}=
       shell: bash
 
-    - name: Exit if not same
-      if: ${{ env.DYN_DIGEST != env.S3_ETAG }}
-      run: |
-        echo DYN_DIGEST-${{ env.DYN_DIGEST }}
-        echo S3_ETAG-${{ env.S3_ETAG }}
-        if [[ ${{ env.DYN_DIGEST }} != ${{ env.S3_ETAG }} ]]; then
-          echo "ERROR!!!!!"
-          echo "Etag in state file not same as digest in DynamoDB table"
-          echo "Another deploy still is inprocess. Please wait untill all commits and checks will be passed and restart this workflow"
-          echo "Also might be need to remove DynamoDB table - lock-dynamo-state${{ env.TEMPENV_VERSION }}-terraform-state"
-          exit 1
-        else
-          echo DEPLOY
-        fi
-      shell: bash
+    # - name: Exit if not same
+    #   if: ${{ env.DYN_DIGEST != env.S3_ETAG }}
+    #   run: |
+    #     echo DYN_DIGEST-${{ env.DYN_DIGEST }}
+    #     echo S3_ETAG-${{ env.S3_ETAG }}
+    #     if [[ ${{ env.DYN_DIGEST }} != ${{ env.S3_ETAG }} ]]; then
+    #       echo "ERROR!!!!!"
+    #       echo "Etag in state file not same as digest in DynamoDB table"
+    #       echo "Another deploy still is inprocess. Please wait untill all commits and checks will be passed and restart this workflow"
+    #       echo "Also might be need to remove DynamoDB table - lock-dynamo-state${{ env.TEMPENV_VERSION }}-terraform-state"
+    #       exit 1
+    #     else
+    #       echo DEPLOY
+    #     fi
+    #   shell: bash
 
 #################################
 
