Change order for creating dynamodb table

diff --git a/deploy-infra/action.yml b/deploy-infra/action.yml
--- a/deploy-infra/action.yml
+++ b/deploy-infra/action.yml
@@ -52,15 +52,15 @@ runs:
         echo "DYN_DIGEST=$(aws dynamodb scan --table-name lock-dynamo-state${{ env.TEMPENV_VERSION }}-terraform-state | jq '.Items | .[] | select(.Digest.S != null) | .Digest.S')" >> $GITHUB_ENV
       shell: bash
 
-    # - name: Exit if not same
-    #   if: ${{ env.DYN_DIGEST != env.S3_ETAG }}
-    #   run: |
-    #     echo "ERROR!!!!!"
-    #     echo "Etag in state file not same as digest in DynamoDB table"
-    #     echo "Another deploy still is inprocess. Please wait untill all commits and checks will be passed and restart this workflow"
-    #     echo "Also might be need to remove DynamoDB table - lock-dynamo-state${{ env.TEMPENV_VERSION }}-terraform-state"
-    #     exit 1
-    #   shell: bash
+    - name: Exit if not same
+      if: ${{ env.DYN_DIGEST != env.S3_ETAG }}
+      run: |
+        echo "ERROR!!!!!"
+        echo "Etag in state file not same as digest in DynamoDB table"
+        echo "Another deploy still is inprocess. Please wait untill all commits and checks will be passed and restart this workflow"
+        echo "Also might be need to remove DynamoDB table - lock-dynamo-state${{ env.TEMPENV_VERSION }}-terraform-state"
+        exit 1
+      shell: bash
 
 #################################
 
